<a href="https://colab.research.google.com/github/zilver666/229352-StatisticalLearning-Lab/blob/main/Lab07_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [25]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [26]:
scalar_tensor = torch.tensor(5)
print(scalar_tensor)

tensor(5)


### Convert a tensor to scalar

In [27]:
scalar_value = scalar_tensor.item()
print(scalar_value)

5


### Creating 2D tensor

In [28]:
matrix_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


## Tensor and Numpy

### Convert from tensor to numpy array

In [29]:
numpy_array = matrix_tensor.numpy()
print(numpy_array)

[[1 2 3]
 [4 5 6]]


### Convert from numpy array to tensor

In [30]:
tensor_from_numpy = torch.from_numpy(numpy_array)
print(tensor_from_numpy)

tensor([[1, 2, 3],
        [4, 5, 6]])


## PyTorch and GPU

check if GPU is available

In [31]:
torch.cuda.is_available()

True

In [32]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [33]:
torch.cuda.device_count()

1

In [34]:
torch.cuda.current_device()

0

## Basic operations

In [35]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(a+b)
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


### Matrix multiplication

In [36]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
print(torch.matmul(A,B))

tensor([[19, 22],
        [43, 50]])


### Matrix transpose

In [37]:
A = torch.tensor([[1,2],[3,4]])
print(A.T)

tensor([[1, 3],
        [2, 4]])


## Creating a specific type of tensor

In [38]:
zeros = torch.zeros(2,2)
ones = torch.ones(2,2)
rand = torch.randn(2,2)

## Tensor's shape

### Checking the shape of a tensor

In [39]:
x = torch.zeros(3,4)
print(x.shape)

torch.Size([3, 4])


### Changing the shape of a tensor

In [40]:
x = torch.zeros(3,4)
print(x.reshape(2,6).shape)

torch.Size([2, 6])


In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [41]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
print(torch.stack((x,y)))

tensor([[1, 2],
        [3, 4]])


In [42]:
# concatenate
x = torch.tensor([[1,2]])
y = torch.tensor([[3,4]])
print(torch.cat((x,y),dim=0))

tensor([[1, 2],
        [3, 4]])


### Squeezing a tensor (removing an extra dimension)

In [43]:
x = torch.zeros(1,3,1)
print(x.shape)

torch.Size([1, 3, 1])


In [44]:
y = x.squeeze()
print(y.shape)

torch.Size([3])


### Unsqueezing a tensor (adding an extra dimension)

In [45]:
# H.shape = (6, )
H = torch.zeros(6)
H_unsqueezed = H.unsqueeze(0)
print(H_unsqueezed.shape)

torch.Size([1, 6])


## Indexing

In [46]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [47]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [48]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

ones = torch.ones(200, 1)

X = torch.cat((ones, X), dim=1)

y = X @ b + e

b_hat = torch.inverse(X.T @ X) @ X.T @ y

y_hat = X @ b_hat

y_np = y.numpy()
y_hat_np = y_hat.numpy()

mse = np.mean((y_np - y_hat_np)**2)
print("MSE=", mse)

MSE= 0.9980163
